### ISSUE TITLE
Latest Chrome Driver

### ISSUE THREAD

**Issue by tjventurini** [kynetiv/docker-selenium-pi#2]
Hi there and thank you for the effort of building the chrome standalone selenium for arm. Although I was wondering if you could upgrade to the latest chromedriver (v2.45).

Thank you!

**Comment by kynetiv** [comment]
Hi @tjventurini, I've updated this repo and the built docker images to the latest [release 3.141.59-dubnium](https://github.com/SeleniumHQ/docker-selenium/releases/tag/3.141.59-dubnium). The built Standalone Chromium docker image is available here if you like to give it a try:

`kynetiv/selenium-standalone-chromium-pi:3.141.59-dubnium`

`Chromium-chromedriver` has a different package and version number unlike the google-chrome chromedriver (v2.45). I'm not sure how these relate exactly; however, I've updated to the latest chromium driver version [(v71.0.3578.80)](https://chromedriver.storage.googleapis.com/index.html?path=71.0.3578.80/).
